#FROM python:3.8.3-buster
FROM python:3.7-slim
#FROM python:3
#FROM frolvlad/alpine-python3

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .
COPY docker-entrypoint.sh /usr/local/bin/
COPY cmrm /tmp/
RUN ln -s usr/local/bin/docker-entrypoint.sh /entrypoint.sh # backwards compat

EXPOSE 30000
#ENTRYPOINT ["/usr/src/app/cmrm", "/usr/local/bin/docker-entrypoint.sh", "3"]
ENTRYPOINT ["docker-entrypoint.sh"]
#CMD [ "python", "./test_flask.py" ]

